<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountryContinentSeeder extends Seeder
{
    public function run()
    {
        $countries = [
            ['name' => 'Algeria', 'code' => 'DZ', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Angola', 'code' => 'AO', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Benin', 'code' => 'BJ', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Botswana', 'code' => 'BW', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Burkina Faso', 'code' => 'BF', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Burundi', 'code' => 'BI', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Cameroon', 'code' => 'CM', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Cape Verde', 'code' => 'CV', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Central African Republic', 'code' => 'CF', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Chad', 'code' => 'TD', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Comoros', 'code' => 'KM', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Congo (Brazzaville)', 'code' => 'CG', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Congo (Kinshasa)', 'code' => 'CD', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Djibouti', 'code' => 'DJ', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Egypt', 'code' => 'EG', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Equatorial Guinea', 'code' => 'GQ', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Eritrea', 'code' => 'ER', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Eswatini', 'code' => 'SZ', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Ethiopia', 'code' => 'ET', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Gabon', 'code' => 'GA', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Gambia', 'code' => 'GM', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Ghana', 'code' => 'GH', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Guinea', 'code' => 'GN', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Guinea-Bissau', 'code' => 'GW', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Ivory Coast', 'code' => 'CI', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Kenya', 'code' => 'KE', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Lesotho', 'code' => 'LS', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Liberia', 'code' => 'LR', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Libya', 'code' => 'LY', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Madagascar', 'code' => 'MG', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Malawi', 'code' => 'MW', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Mali', 'code' => 'ML', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Mauritania', 'code' => 'MR', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Mauritius', 'code' => 'MU', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Morocco', 'code' => 'MA', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Mozambique', 'code' => 'MZ', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Namibia', 'code' => 'NA', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Niger', 'code' => 'NE', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Nigeria', 'code' => 'NG', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Rwanda', 'code' => 'RW', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Sao Tome and Principe', 'code' => 'ST', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Senegal', 'code' => 'SN', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Seychelles', 'code' => 'SC', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Sierra Leone', 'code' => 'SL', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Somalia', 'code' => 'SO', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'South Africa', 'code' => 'ZA', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'South Sudan', 'code' => 'SS', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Sudan', 'code' => 'SD', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Tanzania', 'code' => 'TZ', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Togo', 'code' => 'TG', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Tunisia', 'code' => 'TN', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Uganda', 'code' => 'UG', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Zambia', 'code' => 'ZM', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Zimbabwe', 'code' => 'ZW', 'continent_name' => 'Africa', 'continent_code' => 'AF'],
            ['name' => 'Antarctica', 'code' => 'AQ', 'continent_name' => 'Antarctica', 'continent_code' => 'AN'],
            ['name' => 'Afghanistan', 'code' => 'AF', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Armenia', 'code' => 'AM', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Azerbaijan', 'code' => 'AZ', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Bahrain', 'code' => 'BH', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Bangladesh', 'code' => 'BD', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Bhutan', 'code' => 'BT', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Brunei', 'code' => 'BN', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Cambodia', 'code' => 'KH', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'China', 'code' => 'CN', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Cyprus', 'code' => 'CY', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Georgia', 'code' => 'GE', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'India', 'code' => 'IN', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Indonesia', 'code' => 'ID', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Iran', 'code' => 'IR', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Iraq', 'code' => 'IQ', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Israel', 'code' => 'IL', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Japan', 'code' => 'JP', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Jordan', 'code' => 'JO', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Kazakhstan', 'code' => 'KZ', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Kuwait', 'code' => 'KW', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Kyrgyzstan', 'code' => 'KG', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Laos', 'code' => 'LA', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Lebanon', 'code' => 'LB', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Malaysia', 'code' => 'MY', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Maldives', 'code' => 'MV', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Mongolia', 'code' => 'MN', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Myanmar (Burma)', 'code' => 'MM', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Nepal', 'code' => 'NP', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'North Korea', 'code' => 'KP', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Oman', 'code' => 'OM', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Pakistan', 'code' => 'PK', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Palestine', 'code' => 'PS', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Philippines', 'code' => 'PH', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Qatar', 'code' => 'QA', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Saudi Arabia', 'code' => 'SA', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Singapore', 'code' => 'SG', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'South Korea', 'code' => 'KR', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Sri Lanka', 'code' => 'LK', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Syria', 'code' => 'SY', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Tajikistan', 'code' => 'TJ', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Thailand', 'code' => 'TH', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Timor-Leste', 'code' => 'TL', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Turkey', 'code' => 'TR', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Turkmenistan', 'code' => 'TM', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'United Arab Emirates', 'code' => 'AE', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Uzbekistan', 'code' => 'UZ', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Vietnam', 'code' => 'VN', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Yemen', 'code' => 'YE', 'continent_name' => 'Asia', 'continent_code' => 'AS'],
            ['name' => 'Albania', 'code' => 'AL', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Andorra', 'code' => 'AD', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Austria', 'code' => 'AT', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Belarus', 'code' => 'BY', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Belgium', 'code' => 'BE', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Bulgaria', 'code' => 'BG', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Croatia', 'code' => 'HR', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Czech Republic', 'code' => 'CZ', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Denmark', 'code' => 'DK', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Estonia', 'code' => 'EE', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Finland', 'code' => 'FI', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'France', 'code' => 'FR', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Germany', 'code' => 'DE', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Greece', 'code' => 'GR', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Hungary', 'code' => 'HU', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Iceland', 'code' => 'IS', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Ireland', 'code' => 'IE', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Italy', 'code' => 'IT', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Latvia', 'code' => 'LV', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Liechtenstein', 'code' => 'LI', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Lithuania', 'code' => 'LT', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Luxembourg', 'code' => 'LU', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Malta', 'code' => 'MT', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Moldova', 'code' => 'MD', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Monaco', 'code' => 'MC', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Montenegro', 'code' => 'ME', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Netherlands', 'code' => 'NL', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'North Macedonia', 'code' => 'MK', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Norway', 'code' => 'NO', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Poland', 'code' => 'PL', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Portugal', 'code' => 'PT', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Romania', 'code' => 'RO', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Russia', 'code' => 'RU', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'San Marino', 'code' => 'SM', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Serbia', 'code' => 'RS', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Slovakia', 'code' => 'SK', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Slovenia', 'code' => 'SI', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Spain', 'code' => 'ES', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Sweden', 'code' => 'SE', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Switzerland', 'code' => 'CH', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Ukraine', 'code' => 'UA', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'United Kingdom', 'code' => 'GB', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Vatican City', 'code' => 'VA', 'continent_name' => 'Europe', 'continent_code' => 'EU'],
            ['name' => 'Antigua and Barbuda', 'code' => 'AG', 'continent_name' => 'North America', 'continent_code' => 'NA'],
            ['name' => 'Bahamas', 'code' => 'BS', 'continent_name' => 'North America', 'continent_code' => 'NA'],
            ['name' => 'Barbados', 'code' => 'BB', 'continent_name' => 'North America', 'continent_code' => 'NA'],
            ['name' => 'Belize', 'code' => 'BZ', 'continent_name' => 'North America', 'continent_code' => 'NA'],
            ['name' => 'Canada', 'code' => 'CA', 'continent_name' => 'North America', 'continent_code' => 'NA'],
            ['name' => 'Costa Rica', 'code' => 'CR', 'continent_name' => 'North America', 'continent_code' => 'NA'],
            ['name' => 'Cuba', 'code' => 'CU', 'continent_name' => 'North America', 'continent_code' => 'NA'],
            ['name' => 'Dominica', 'code' => 'DM', 'continent_name' => 'North America', 'continent_code' => 'NA'],
            ['name' => 'Dominican Republic', 'code' => 'DO', 'continent_name' => 'North America', 'continent_code' => 'NA'],
            ['name' => 'El Salvador', 'code' => 'SV', 'continent_name' => 'North America', 'continent_code' => 'NA'],
            ['name' => 'Grenada', 'code' => 'GD', 'continent_name' => 'North America', 'continent_code' => 'NA'],
            ['name' => 'Guatemala', 'code' => 'GT', 'continent_name' => 'North America', 'continent_code' => 'NA'],
            ['name' => 'Haiti', 'code' => 'HT', 'continent_name' => 'North America', 'continent_code' => 'NA'],
            ['name' => 'Honduras', 'code' => 'HN', 'continent_name' => 'North America', 'continent_code' => 'NA'],
            ['name' => 'Jamaica', 'code' => 'JM', 'continent_name' => 'North America', 'continent_code' => 'NA'],
            ['name' => 'Mexico', 'code' => 'MX', 'continent_name' => 'North America', 'continent_code' => 'NA'],
            ['name' => 'Nicaragua', 'code' => 'NI', 'continent_name' => 'North America', 'continent_code' => 'NA'],
            ['name' => 'Panama', 'code' => 'PA', 'continent_name' => 'North America', 'continent_code' => 'NA'],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KN', 'continent_name' => 'North America', 'continent_code' => 'NA'],
            ['name' => 'Saint Lucia', 'code' => 'LC', 'continent_name' => 'North America', 'continent_code' => 'NA'],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'continent_name' => 'North America', 'continent_code' => 'NA'],
            ['name' => 'Trinidad and Tobago', 'code' => 'TT', 'continent_name' => 'North America', 'continent_code' => 'NA'],
            ['name' => 'United States', 'code' => 'US', 'continent_name' => 'North America', 'continent_code' => 'NA'],
            ['name' => 'Australia', 'code' => 'AU', 'continent_name' => 'Oceania', 'continent_code' => 'OC'],
            ['name' => 'Fiji', 'code' => 'FJ', 'continent_name' => 'Oceania', 'continent_code' => 'OC'],
            ['name' => 'Kiribati', 'code' => 'KI', 'continent_name' => 'Oceania', 'continent_code' => 'OC'],
            ['name' => 'Marshall Islands', 'code' => 'MH', 'continent_name' => 'Oceania', 'continent_code' => 'OC'],
            ['name' => 'Micronesia', 'code' => 'FM', 'continent_name' => 'Oceania', 'continent_code' => 'OC'],
            ['name' => 'Nauru', 'code' => 'NR', 'continent_name' => 'Oceania', 'continent_code' => 'OC'],
            ['name' => 'New Zealand', 'code' => 'NZ', 'continent_name' => 'Oceania', 'continent_code' => 'OC'],
            ['name' => 'Palau', 'code' => 'PW', 'continent_name' => 'Oceania', 'continent_code' => 'OC'],
            ['name' => 'Papua New Guinea', 'code' => 'PG', 'continent_name' => 'Oceania', 'continent_code' => 'OC'],
            ['name' => 'Samoa', 'code' => 'WS', 'continent_name' => 'Oceania', 'continent_code' => 'OC'],
            ['name' => 'Solomon Islands', 'code' => 'SB', 'continent_name' => 'Oceania', 'continent_code' => 'OC'],
            ['name' => 'Tonga', 'code' => 'TO', 'continent_name' => 'Oceania', 'continent_code' => 'OC'],
            ['name' => 'Tuvalu', 'code' => 'TV', 'continent_name' => 'Oceania', 'continent_code' => 'OC'],
            ['name' => 'Vanuatu', 'code' => 'VU', 'continent_name' => 'Oceania', 'continent_code' => 'OC'],
        ];

        DB::table('countries_master')->insert($countries);
    }
}
